title: "Чикагский Философский Форум"
author: "Чикагский Философский Форум"
description: "Клуб Чикагских Любомудров"
more: "читать далее"
baseurl: "/russianchicagophilosophyforum"

prose:
  rooturl: _posts
  media: assets
  metadata:
    _posts:
      - name: title
        field:
          element: text
          label: title
      - name: date
        field:
          element: hidden
          value: CURRENT_DATETIME
      - name: author
        field:
          element: text
          placeholder: "Ваше Имя"
      - name: categories
        field:
          element: select
          value: пост
          options:
            - name: 'пост'
              value: 'пост'
            - name: 'объявление'
              value: 'объявление' 

comments:
  disqus: "russianchicagophilosophyforum"

exclude:
  - node_modules/
  - tmp/


style:
  # body: "whitesmoke"
  padding: 33%
  anchor: "#46f"
  serif-heading: true
  nav: "#181818"
#  headline: "#06f"
  description: "white"
  article:
    odd: "#ffffff"
    even: "#222222"

links:
  - youtube: "https://www.youtube.com/channel/UCee5CL9-ksaF3tHnqCuNa_Q"
  # - github: "https://github.com/me/"
  # - twitter: "https://twitter.com/me/"
  # - google-plus: "https://plus.google.com/+me"
  # - reddit: "https://www.reddit.com/user/me/"
  # - steam: "http://steamcommunity.com/id/me/"

paginate: 10
excerpt_separator: "\n\n\n" # excerpt ends after two blank lines
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
gems: [jekyll-feed] # include feed plugin (supported by gh-pages)
